### ISSUE TITLE
Add an example for UseMiddleware()

### ISSUE THREAD

**Issue by strpipe** [aspnet/AspNetDocs.de-de#1]
Hey, 
I took a while to notice that there is a UseMiddleware-Method. 
Adding an example to this page could prevent others from missing out this feature too.

You can find an example here: https://docs.microsoft.com/de-de/aspnet/core/migration/http-modules?view=aspnetcore-2.2

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 9898482c-fa54-7ce2-1716-d14fbe03990d
* Version Independent ID: 3926c686-0ccc-f9fe-ca52-0134612a1623
* Content: [ASP.NET Core-Middleware](https://docs.microsoft.com/de-de/aspnet/core/fundamentals/middleware/index?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/middleware/index.md](https://github.com/aspnet/AspNetDocs.de-de/blob/live/aspnetcore/fundamentals/middleware/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Recommend closing because this is covered in https://docs.microsoft.com/aspnet/core/fundamentals/middleware/write

**Comment by CeciAc** [comment]
Hello, @strpipe

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review document https://docs.microsoft.com/aspnet/core/fundamentals/middleware/write 
For this reason we are closing this issue since it is duplicated.

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards,
Microsoft DOCS International Team
